(function(){
'use strict';
const M=window.RetirementModel,D=window.RetirementData,$=id=>document.getElementById(id);
let state={...M.defaults},policies=M.samples(state.age),comparison=null,result=null,seq=0,toastTimer=null;
const variants={},names={none:'無額外事故',medical:'住院／手術',cancer:'罹癌治療',accident:'意外傷害',ltc:'長期照顧',home:'在宅急症'};
const money=v=>Math.round(v).toLocaleString('zh-TW'),wan=v=>(v/10000).toLocaleString('zh-TW',{maximumFractionDigits:1}),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3500);}
function refs(ids){return '<span class="refs">'+(ids||[]).map(id=>{const s=D.sources.find(x=>x.id===id);return s?'<a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer" title="'+esc(s.title)+'">'+id+'</a>':'';}).join('')+'</span>';}
function syncForm(){Object.keys(M.defaults).forEach(k=>{if(!$(k))return;if(typeof state[k]==='boolean')$(k).checked=state[k];else $(k).value=state[k];});$('ageValue').value=state.age;$('eventAge').min=state.age;$('eventAge').max=state.horizon;}
function toggleTab(name){document.querySelectorAll('[data-tab]').forEach(t=>{const selected=t.dataset.tab===name;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;$('panel-'+t.dataset.tab).hidden=!selected;});if(name==='catalog')renderCatalog();if(name==='policies')renderPolicies();}
function stat(label,value,unit,note,delta=''){return '<div class="stat"><div class="stat-label">'+label+'</div><strong>'+value+(unit?'<span>'+unit+'</span>':'')+'</strong><small>'+note+'</small>'+(delta?'<small class="delta">'+delta+'</small>':'')+'</div>';}
function refresh(){
 try{M.validate(state);result=M.simulate(state,policies);$('formError').hidden=true;}catch(e){$('formError').textContent='請檢查輸入：'+e.message+'。目前結果仍為上次有效試算。';$('formError').hidden=false;return;}
 policies.filter(p=>p.rateAuto).forEach(p=>{p.premium=state.age===60&&state.sex==='male'&&state.health==='normal'?5700:null;});
 $('ageValue').value=state.age;$('policyCount').textContent=policies.length;$('eventAge').min=state.age;$('eventAge').max=state.horizon;
 const missing=policies.filter(p=>p.premium==null&&p.end>=state.age&&p.payEnd>=state.age);const unknownBenefits=policies.filter(p=>p.product&&p.amount===0);
 $('unknownNotice').hidden=!result.unknown&&!unknownBenefits.length;
 $('unknownNotice').textContent=result.unknown?'有'+missing.length+'張保單尚未填保費，未知保費未扣除，餘額偏高。本方案估算不完整；請到「我的保障」填入報價。':unknownBenefits.length+'張具名商品的情境給付尚未填入，暫以0試算，請核對條款後補足。';
 const suffix=result.unknown?'已知部分；尚缺報價':(result.currentPremium>state.budget?'超出預算 '+money(result.currentPremium-state.budget)+'元':'預算剩餘 '+money(state.budget-result.currentPremium)+'元');
 const delta=comparison&&!result.unknown&&!comparison.result.unknown?'相較A '+(result.endFund-comparison.result.endFund>=0?'+':'')+wan(result.endFund-comparison.result.endFund)+'萬元':'';
 $('stats').innerHTML=stat('準備金首次不足',result.exhausted??'可支應',result.exhausted?'歲':'','規劃至'+state.horizon+'歲'+(result.unknown?' · 估算不完整':''))+stat('今年方案保費',money(result.currentPremium),'元／年',suffix)+stat('退休後累計保費',wan(result.retirementPremium),'萬元','按設定費率成長；非正式報價')+stat(state.horizon+'歲年末準備金',wan(result.endFund),'萬元','當年購買力 '+wan(result.rows.at(-1).realFund)+'萬元',delta);
 $('costField').hidden=state.scenario==='ltc'||state.scenario==='none';document.querySelectorAll('.ltc-field').forEach(e=>e.hidden=state.scenario!=='ltc');document.querySelectorAll('.home-field').forEach(e=>e.hidden=state.scenario!=='home');$('stopAgeField').hidden=!state.stopRenewal;
 let note=state.scenario==='none'?'未設定額外事故；已計退休後例行自付醫療。':state.meets?'假設符合理賠條件，依填入給付與期限近似計算。':'目前設定不符合理賠條件，事故給付以0計算。';
 if(state.scenario==='ltc'&&state.eventAge+state.careYears-1>state.horizon)note+=' 照護期間超出規劃終點，結果只計至'+state.horizon+'歲。';
 if(state.scenario==='home'&&(state.homeDisease==='other'||state.homeMode==='early'))note+=' HJL排除此收案情境；其他契約須確認符合條件。';
 $('scenarioResult').innerHTML='<div><small>情境總費用</small><strong>'+wan(result.totalCost)+'萬</strong></div><div><small>依設定可領給付</small><strong>'+wan(result.totalBenefit)+'萬</strong></div><div><small>事故保障缺口</small><strong>'+wan(result.eventGap)+'萬</strong></div><p>'+note+' 保障缺口尚未扣準備金。</p>';
 renderChart();renderCoverage();
 $('strategyTitle').textContent=state.age+'歲的盤點重點';$('strategy').innerHTML=M.priority(state.age,state.debt+state.support>state.familyAssets).map(p=>'<div class="strategy-item"><b>'+M.types[p.type]+'</b><span>'+p.level+'</span><p>'+p.text+'</p></div>').join('');
 $('annualRows').innerHTML=result.rows.map(r=>'<tr class="'+(r.cost?'event-row ':'')+(r.age===state.retire?'retire-row':'')+'"><td>'+r.age+(r.age===state.retire?' · 退休':'')+'</td>'+['income','expenses','premium','cost','benefit','net','fund'].map(k=>'<td class="'+(r[k]<0?'negative':'')+'">'+money(r[k])+(k==='premium'&&r.unknown?'＋未知':'')+'</td>').join('')+'</tr>').join('');
 if(!$('panel-catalog').hidden)renderCatalog();
}
function renderCoverage(){
 $('coverageTitle').textContent=state.eventAge+'歲的六大保障檢視';
 $('coverage').innerHTML=Object.entries(M.types).map(([type,title])=>{const active=policies.filter(p=>p.type===type&&M.active(p,state.eventAge,state));const expired=policies.filter(p=>p.type===type&&!M.active(p,state.eventAge,state)).length;let amount=result.coverage[type],unit='元';let text=expired?expired+'張當年未有效；另核對續保與起保':'依當年有效保單設定';if(type==='ltc')unit='元／月等值';if(type==='home'){amount=active.reduce((v,p)=>v+M.eventBenefits({...state,scenario:'home',meets:true},[p],state.eventAge),0);text='依所設天數／疾病／模式計算；需符合條款';}if(type==='life')text='家庭責任缺口 '+wan(result.lifeGap)+'萬元（以同年死亡保障檢視）';return '<div class="coverage-item"><div class="type">'+title+'<span>'+active.length+'張有效</span></div><div class="number">'+money(amount)+' <small style="display:inline">'+unit+'</small></div><small>'+text+'</small></div>';}).join('');
}
function renderChart(){
 const W=850,H=280,L=62,R=20,T=26,B=34,all=result.rows,ar=comparison?.result.rows||[];const minAge=Math.min(state.age,ar[0]?.age??state.age),maxAge=Math.max(state.horizon,ar.at(-1)?.age??state.horizon);const values=[0,...all.flatMap(r=>[r.fund,r.baseFund]),...ar.map(r=>r.fund)];let lo=Math.min(...values),hi=Math.max(...values);if(hi===lo)hi=lo+10000;const pad=(hi-lo)*.08;lo-=pad;hi+=pad;const x=age=>L+(age-minAge)/(maxAge-minAge||1)*(W-L-R),y=value=>T+(hi-value)/(hi-lo)*(H-T-B),line=(rows,key)=>rows.map((r,i)=>(i?'L':'M')+x(r.age).toFixed(2)+','+y(r[key]).toFixed(2)).join(' ');
 let svg='<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="專用準備金年末餘額圖；完整數值見逐年明細"><title>目前情境、無額外事故及方案A的準備金比較</title><defs><linearGradient id="fundFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#16a287" stop-opacity=".16"/><stop offset="1" stop-color="#16a287" stop-opacity="0"/></linearGradient></defs>';
 for(let i=0;i<5;i++){const value=lo+(hi-lo)*i/4;svg+='<line class="grid-line" x1="'+L+'" x2="'+(W-R)+'" y1="'+y(value)+'" y2="'+y(value)+'"/><text x="'+(L-10)+'" y="'+(y(value)+4)+'" text-anchor="end">'+Math.round(value/10000).toLocaleString('zh-TW')+'</text>';}
 svg+='<line class="zero" x1="'+L+'" x2="'+(W-R)+'" y1="'+y(0)+'" y2="'+y(0)+'"/>';
 const area=line(all,'fund')+' L'+x(all.at(-1).age)+','+y(0)+' L'+x(all[0].age)+','+y(0)+' Z';svg+='<path d="'+area+'" fill="url(#fundFill)"/>';
 for(const [age,label,color] of [[state.retire,'退休','#b6c7d7'],[state.eventAge,state.scenario==='none'?'':names[state.scenario],'#bee0d4']]){if(age>=minAge&&age<=maxAge&&label)svg+='<line x1="'+x(age)+'" x2="'+x(age)+'" y1="'+T+'" y2="'+(H-B)+'" stroke="'+color+'" stroke-dasharray="4 4"/><text x="'+(x(age)+5)+'" y="17">'+age+'歲 '+label+'</text>';}
 svg+='<path d="'+line(all,'baseFund')+'" fill="none" stroke="#96aabb" stroke-width="2" stroke-dasharray="5 5"/>';
 if(comparison)svg+='<path d="'+line(ar,'fund')+'" fill="none" stroke="#3266ca" stroke-width="2"/>';
 svg+='<path d="'+line(all,'fund')+'" fill="none" stroke="#077f69" stroke-width="3" stroke-linejoin="round"/>';
 const ageTicks=new Set([minAge,maxAge]);for(let age=Math.ceil(minAge/10)*10;age<=maxAge;age+=10)if(age>minAge+2&&age<maxAge-2)ageTicks.add(age);for(const age of [...ageTicks].sort((a,b)=>a-b))svg+='<text x="'+x(age)+'" y="'+(H-8)+'" text-anchor="middle">'+age+'歲</text>';
 all.forEach((r,i)=>{svg+='<circle data-row="'+i+'" cx="'+x(r.age)+'" cy="'+y(r.fund)+'" r="7" fill="transparent" tabindex="0" aria-label="'+r.age+'歲餘額'+money(r.fund)+'元"><title>'+r.age+'歲：'+money(r.fund)+'元</title></circle>';});svg+='</svg>';$('chart').innerHTML=svg;$('compareLegend').hidden=!comparison;$('clearCompare').hidden=!comparison;readout(all.at(-1));
 $('chart').querySelectorAll('[data-row]').forEach(e=>{const show=()=>readout(all[Number(e.dataset.row)]);e.addEventListener('pointerenter',show);e.addEventListener('focus',show);e.addEventListener('click',show);});
}
function readout(r){$('chartReadout').textContent=r.age+'歲｜年末餘額 '+wan(r.fund)+'萬元｜年度收支 '+wan(r.net)+'萬元'+(comparison?'｜A：'+comparison.state.age+'歲起算／'+names[comparison.state.scenario]:'')+'｜退休年度收支首次不足：'+(result.firstShortfall===null?'規劃期內未出現':result.firstShortfall+'歲');}
function pField(p,key,label,min=0,max=1000000000,step=1){return '<label>'+label+'<input data-policy="'+esc(p.id)+'" data-key="'+key+'" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(p[key]??'')+'" '+(p[key]==null?'placeholder="請填正式報價"':'')+'></label>';}
function renderPolicies(){
 $('policyList').innerHTML=policies.length?policies.map(p=>{const title=p.type==='ltc'?'每月等值分期給付（元）':p.type==='home'?(p.basis==='event'?'每次給付（元）':'照護日額（元）'):p.type==='life'?'死亡保障（元）':p.type==='cancer'?'事故可領一次金（元）':'費用補償上限（元）';const amountMin=p.product==='JHA'||p.product==='HJL'?500:p.product==='1HHI'?2000:0;let top='<div class="policy-head"><div><h4>'+esc(p.label)+'</h4> <span class="tag '+(p.demo?'demo':p.product?'real':'')+'">'+(p.demo?'示範假設':p.product?'商品條件＋自行填報':'使用者設定')+'</span><small>'+esc(p.company)+' · '+M.types[p.type]+(p.product?' · '+esc(p.product):'')+'</small></div><button class="delete-policy" data-delete="'+p.id+'" aria-label="移除'+esc(p.label)+'">移除</button></div>';
 let fields='<div class="policy-fields">'+pField(p,'premium','目前年度保費（元）',0,100000000,1)+pField(p,'amount',title,amountMin,p.amountMax||1000000000,p.type==='home'&&p.product==='1HHI'?1000:1)+pField(p,'end','保障末年（含）',0,105)+pField(p,'payEnd','繳費末年（含）',0,105)+'</div>';
 let more='<details class="policy-more"><summary>名稱、給付限制與保費成長</summary><div class="policy-fields"><label>公司／註記<input data-policy="'+p.id+'" data-key="company" maxlength="80" value="'+esc(p.company)+'"></label><label>方案名稱<input data-policy="'+p.id+'" data-key="label" maxlength="100" value="'+esc(p.label)+'"></label>';
 if(!p.product)more+='<label>險種<select data-policy="'+p.id+'" data-key="type">'+Object.entries(M.types).map(([k,v])=>'<option value="'+k+'" '+(p.type===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label>';
 more+=pField(p,'start','保障起始年齡',0,105)+pField(p,'growth','保費年增率 %（假設）',0,20,.5);
 if(p.type==='ltc')more+=pField(p,'maxYears','分期金最多給付年數',1,30)+pField(p,'waiting','事故首年免責月數',0,12)+pField(p,'benefitGrowth','分期金單利年增 %',0,10,.5);
 if(p.type==='home'&&!p.product)more+='<label>給付方式<select data-policy="'+p.id+'" data-key="basis"><option value="daily" '+(p.basis==='daily'?'selected':'')+'>按日</option><option value="event" '+(p.basis==='event'?'selected':'')+'>按次</option></select></label>';
 more+='</div><label class="policy-check"><input data-policy="'+p.id+'" data-key="nonGuaranteed" type="checkbox" '+(p.nonGuaranteed?'checked':'')+'>非保證續保（會套用中斷情境）</label></details>';
 const alerts=(p.premium==null?'尚缺年度保費；未計入費用。 ':'')+(p.amount===0?'尚未設定可領給付。 ':'')+(p.end<state.age?'保障末年早於目前年齡。 ':'')+(p.start>state.age?'尚未到保障起始年齡。 ':'');
 return '<article class="policy-card">'+top+fields+more+(alerts?'<p class="policy-alert">'+alerts+'</p>':'')+'<p class="policy-note">'+(p.product?'具名商品只計所填保障部分。保障／繳費末年及給付數值請依個別契約確認；增幅為假設。 '+refs(p.refs):'此保費與保障為'+(p.demo?'示範假設':'使用者輸入')+'，並非任何公司的正式費率。')+'</p></article>';}).join(''):'<section class="card"><h3>尚未加入保障</h3><p class="muted">新增自訂保單，或從跨公司比較加入商品，再填入正式報價與給付。</p></section>';
}
function eligibility(p){const v=p.variants?.[variants[p.id]??0]||p;const known=v.min!=null&&v.max!=null;const allowed=!known||(state.age>=v.min&&state.age<=v.max);return {v,known,allowed,text:known?(state.age>=v.min&&state.age<=v.max?'符合公開年齡範圍 · 尚須核保':'超出此年期新投保範圍'):'投保年齡須再查核'};}
function renderCatalog(){
 const type=$('typeFilter').value,company=$('companyFilter').value,existing=$('catalogMode').value==='existing';$('catalogAge').textContent='目前 '+state.age+'歲／'+(state.sex==='male'?'男性':'女性')+(state.health==='condition'?' · 有病史，須另核保':'')+'。僅依公開年齡篩查；目前未建完整性別／年齡費率表。';
 const list=D.catalog.filter(p=>(type==='all'||p.type===type)&&(company==='all'||p.company===company));
 $('catalogList').innerHTML=list.length?list.map(p=>{const e=eligibility(p);const age=e.known?e.v.min+'–'+e.v.max+'歲':'待核對';const term=p.variants?'<label class="variant-field">'+(p.type==='cancer'?'保險年期':'繳費年期')+'<select data-variant="'+p.id+'">'+p.variants.map((v,i)=>'<option value="'+i+'" '+((variants[p.id]??0)===i?'selected':'')+'>'+v.years+'年 · '+v.min+'–'+v.max+'歲</option>').join('')+'</select></label>':'<p class="small">新投保 '+age+(p.end?' · 保障上限摘要 '+p.end+'歲':'')+'</p>';
 return '<article class="product"><span class="company">'+p.company+' / '+M.types[p.type]+'</span><span class="tag">'+p.id+'</span><h4>'+p.name+'</h4><p>'+p.full+'</p>'+term+'<span class="eligibility '+(!e.allowed?'out':'')+'">'+(existing?'已有契約：依原保單核對':e.text)+'</span><p>'+p.detail+'</p><p style="margin-top:8px">'+(p.nonGuaranteed?'一年期，非保證續保。 ':'')+'保費待填正式報價。</p><div class="product-footer">'+refs(p.refs)+(p.researchOnly?'<button data-open="policies" class="outline">以自訂保單填入</button>':'<button data-add="'+p.id+'" class="outline" '+(!existing&&!e.allowed?'disabled':'')+'>加入試算</button>')+'</div></article>';}).join(''):'<div class="card">目前篩選沒有已收錄樣本；不代表該公司沒有此類商品。</div>';
}
function addCatalog(id){const p=D.catalog.find(x=>x.id===id);if(!p||p.researchOnly)return;const e=eligibility(p);if($('catalogMode').value==='new'&&!e.allowed)return;const end=p.end??(p.type==='cancer'&&e.v.years?Math.min(105,state.age+e.v.years-1):95);const payEnd=p.nonGuaranteed||p.id==='MNC'?end:e.v.years?Math.min(end,state.age+e.v.years-1):Math.min(end,state.age+9);const known=p.id==='HJL'&&state.age===60&&state.sex==='male'&&state.health==='normal';policies.push({id:'product-'+(++seq),product:p.id,type:p.type,label:p.full,company:p.company,premium:known?5700:null,growth:p.nonGuaranteed||p.id==='MNC'?4:0,amount:p.type==='home'?p.amount:0,amountMax:p.amountMax,end,payEnd,start:state.age,maxYears:p.maxYears??15,waiting:p.waiting??0,benefitGrowth:p.benefitGrowth??0,basis:p.basis??(p.type==='ltc'?'monthly':p.type==='accident'||p.type==='medical'?'reimbursement':'lump'),nonGuaranteed:!!p.nonGuaranteed,perEventMax:p.perEventMax,refs:p.refs,demo:false,rateAuto:known});refresh();toggleTab('policies');toast(known?'已帶入官方60歲男性案例5,700元；未來增幅仍為假設，請核對報價。':'已加入商品樣本，請填正式報價、保障期限與可領給付。');}
function addCustom(){policies.push({id:'custom-'+(++seq),type:'medical',label:'自訂保單',company:'我的契約／報價',premium:null,growth:0,amount:0,end:85,payEnd:85,start:state.age,maxYears:15,waiting:0,benefitGrowth:0,basis:'reimbursement',nonGuaranteed:false,demo:false});renderPolicies();refresh();toast('請填入自訂保單的年度保費與可領給付。');}
function readControl(el){if(el.type==='checkbox')return el.checked;if(el.type==='number'||el.type==='range')return el.value===''?NaN:Number(el.value);return el.value;}
function profileChange(el){const key=el.id;if(!(key in M.defaults))return;if(!el.checkValidity()){el.reportValidity();return;}const next={...state,[key]:readControl(el)};if(key==='age'||key==='horizon'){next.eventAge=Math.min(next.horizon,Math.max(next.age,next.eventAge));}try{M.validate(next);}catch(e){$('formError').textContent='請檢查輸入：'+e.message;$('formError').hidden=false;return;}state=next;if(key==='age'){policies.filter(p=>p.demo).forEach(p=>p.start=Math.min(p.start,state.age));syncForm();}if(key==='horizon')$('eventAge').value=state.eventAge;refresh();}
function changePolicy(el){const p=policies.find(x=>x.id===el.dataset.policy);if(!p)return;const key=el.dataset.key;let value=readControl(el);if(key==='premium'&&el.value==='')value=null;else if(!el.checkValidity()||(typeof value==='number'&&!Number.isFinite(value))){el.reportValidity();return;}p[key]=value;
 if(key==='premium')p.rateAuto=false;
 if(key==='type'){p.basis=value==='home'?'daily':value==='ltc'?'monthly':value==='medical'||value==='accident'?'reimbursement':'lump';renderPolicies();}refresh();}
function preset(age){state={...M.defaults,age,retire:65,eventAge:75};if(age===40){state.fund=1000000;state.saving=12000;}if(age===65){state.fund=4000000;state.saving=0;}policies=M.samples(age);comparison=null;syncForm();renderPolicies();refresh();toast('已載入'+age+'歲示範情境；數值與保單為可修改假設。');}
document.querySelectorAll('[data-tab]').forEach(btn=>{btn.addEventListener('click',()=>toggleTab(btn.dataset.tab));btn.addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-tab]')];const i=tabs.indexOf(btn);let target;if(e.key==='ArrowRight')target=tabs[(i+1)%tabs.length];if(e.key==='ArrowLeft')target=tabs[(i+tabs.length-1)%tabs.length];if(e.key==='Home')target=tabs[0];if(e.key==='End')target=tabs.at(-1);if(target){e.preventDefault();toggleTab(target.dataset.tab);target.focus();}});});
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)toggleTab(open.dataset.open);const add=e.target.closest('[data-add]');if(add&&!add.disabled)addCatalog(add.dataset.add);const del=e.target.closest('[data-delete]');if(del){policies=policies.filter(p=>p.id!==del.dataset.delete);renderPolicies();refresh();}const pr=e.target.closest('[data-preset]');if(pr)preset(Number(pr.dataset.preset));});
document.addEventListener('input',e=>{if(e.target.dataset.policy)return;profileChange(e.target);});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.policy){changePolicy(el);return;}if(el.dataset.variant){variants[el.dataset.variant]=Number(el.value);renderCatalog();return;}if(['typeFilter','companyFilter','catalogMode'].includes(el.id))renderCatalog();else if(el.tagName==='SELECT'||el.type==='checkbox')profileChange(el);});
// Policy changes are committed after leaving a field, preserving typing and focus.
$('addPolicy').addEventListener('click',addCustom);$('reset').addEventListener('click',()=>{state={...M.defaults};policies=M.samples(state.age);comparison=null;syncForm();renderPolicies();refresh();toast('已回到初始示範。');});
$('pin').addEventListener('click',()=>{comparison={state:structuredClone(state),policies:structuredClone(policies),result:structuredClone(result)};refresh();toast('已記住方案A。現在調整保費或保障，即可對照現金流。');});$('clearCompare').addEventListener('click',()=>{comparison=null;refresh();});
$('sources').innerHTML=D.sources.map(s=>'<article class="source-item"><a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+s.id+' · '+s.title+'</a><p>'+s.note+'</p><p>查核：'+s.date+'</p></article>').join('');
if(window.matchMedia){const mobile=window.matchMedia('(max-width:760px)');$('financeDetails').open=!mobile.matches;mobile.addEventListener?.('change',e=>{$('financeDetails').open=!e.matches;});}
syncForm();renderPolicies();renderCatalog();refresh();
window.RetirementApp={summary:()=>({age:state.age,scenario:state.scenario,policyCount:policies.length,currentPremium:result.currentPremium,eventGap:result.eventGap,endFund:result.endFund,firstShortfall:result.firstShortfall,exhausted:result.exhausted,estimateIncomplete:result.unknown}),configure(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('參數須為物件');const next={...state};for(const [k,v]of Object.entries(input)){if(!(k in M.rangeRules)&&!['scenario','sex','health','meets','stopRenewal','homeDisease','homeMode'].includes(k))throw new Error('未知欄位：'+k);if(k in M.rangeRules&&typeof v!=='number')throw new Error('數值欄位須為number');if(['meets','stopRenewal'].includes(k)&&typeof v!=='boolean')throw new Error('布林欄位格式錯誤');next[k]=v;}for(const [key,vals]of Object.entries({sex:['male','female'],health:['normal','condition'],homeDisease:['soft','urinary','pneumonia','other'],homeMode:['admission','early']}))if(!vals.includes(next[key]))throw new Error(key+'無效');M.validate(next);state=next;if('age' in input)policies.filter(p=>p.demo).forEach(p=>p.start=Math.min(p.start,state.age));syncForm();refresh();renderPolicies();return this.summary();}};
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_retirement_simulation',title:'讀取退休試算',description:'讀取目前頁面已完成的退休保險試算摘要。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>window.RetirementApp.summary()});const properties={};for(const [key,[minimum,maximum]]of Object.entries(M.rangeRules))properties[key]={type:'number',minimum,maximum};properties.scenario={type:'string',enum:['none','medical','cancer','accident','ltc','home']};register({name:'configure_retirement_parameters',title:'設定退休試算參數',description:'修改與可見表單相同的年齡、收入、費用及情境假設，完成重新試算；不購買保險或儲存個人資料。',inputSchema:{type:'object',properties,additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>window.RetirementApp.configure(input)});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
