(function(root){
 'use strict';
 const types={life:'一般壽險',accident:'意外險',medical:'醫療險',cancer:'癌症險',ltc:'長照險',home:'在宅急症'};
 const defaults={age:50,retire:65,horizon:95,sex:'male',health:'normal',fund:2000000,saving:10000,pension:40000,living:32000,regularMedical:20000,budget:60000,inflation:2,medicalInflation:3,returnRate:2,incomeGrowth:0,scenario:'ltc',eventAge:75,eventCost:1000000,careMonthly:60000,careYears:5,homeDays:9,homeDisease:'soft',homeMode:'admission',meets:true,stopRenewal:false,stopAge:75,debt:3000000,support:2000000,familyAssets:1000000};
 const rangeRules={age:[30,85],retire:[30,90],horizon:[85,105],fund:[0,1000000000],saving:[0,10000000],pension:[0,10000000],living:[0,10000000],regularMedical:[0,100000000],budget:[0,100000000],inflation:[0,15],medicalInflation:[0,15],returnRate:[-10,15],incomeGrowth:[0,10],eventAge:[30,105],eventCost:[0,1000000000],careMonthly:[0,10000000],careYears:[1,30],homeDays:[1,60],stopAge:[30,105],debt:[0,1000000000],support:[0,1000000000],familyAssets:[0,1000000000]};
 function validate(s){for(const [k,[lo,hi]] of Object.entries(rangeRules)){if(!Number.isFinite(Number(s[k]))||Number(s[k])<lo||Number(s[k])>hi)throw new Error(k+'超出可設定範圍');}if(s.horizon<s.age||s.eventAge<s.age||s.eventAge>s.horizon)throw new Error('事故年齡須介於目前年齡與規劃終點');if(!['none','medical','cancer','accident','ltc','home'].includes(s.scenario))throw new Error('無效的風險情境');return s;}
 function samples(age){return [
 {id:'demo-life',type:'life',label:'家庭責任保障',company:'示範保單',premium:5000,growth:0,amount:3000000,end:65,payEnd:65,start:age,maxYears:15,waiting:0,benefitGrowth:0,basis:'lump',nonGuaranteed:false,demo:true},
 {id:'demo-accident',type:'accident',label:'傷害醫療準備',company:'示範保單',premium:1800,growth:0,amount:100000,end:80,payEnd:80,start:age,maxYears:15,waiting:0,benefitGrowth:0,basis:'reimbursement',nonGuaranteed:false,demo:true},
 {id:'demo-medical',type:'medical',label:'住院與手術費用',company:'示範保單',premium:14000,growth:4,amount:300000,end:80,payEnd:80,start:age,maxYears:15,waiting:0,benefitGrowth:0,basis:'reimbursement',nonGuaranteed:false,demo:true},
 {id:'demo-cancer',type:'cancer',label:'罹癌一次金',company:'示範保單',premium:6000,growth:3,amount:1000000,end:85,payEnd:85,start:age,maxYears:15,waiting:0,benefitGrowth:0,basis:'lump',nonGuaranteed:false,demo:true},
 {id:'demo-ltc',type:'ltc',label:'長期照顧分期金',company:'示範保單',premium:18000,growth:0,amount:30000,end:95,payEnd:70,start:age,maxYears:15,waiting:3,benefitGrowth:0,basis:'monthly',nonGuaranteed:false,demo:true},
 {id:'demo-home',type:'home',label:'在宅急症日額',company:'示範保單',premium:3000,growth:4,amount:1000,end:80,payEnd:80,start:age,maxYears:15,waiting:0,benefitGrowth:0,basis:'daily',nonGuaranteed:true,demo:true,perEventMax:60}
 ];}
 function active(p,age,s){return age>=p.start&&age<=p.end&&!(p.nonGuaranteed&&s.stopRenewal&&age>=s.stopAge);}
 function premiumAt(p,age,s){if(!active(p,age,s)||age>p.payEnd)return 0;return p.premium==null?null:Number(p.premium)*Math.pow(1+Number(p.growth)/100,age-s.age);}
 function homeBenefit(p,s){if(p.product==='HJL'&&(s.homeMode==='early'||s.homeDisease==='other'))return 0;if(p.basis==='event')return Number(p.amount);let cap=p.perEventMax||60;if(p.product==='HJL')cap=s.homeDisease==='pneumonia'?14:9;return Number(p.amount)*Math.min(s.homeDays,cap);}
 function eventBenefits(s,policies,age){if(!s.meets)return 0;const enabled=policies.filter(p=>p.type===s.scenario&&active(p,age,s));if(s.scenario==='ltc'){return enabled.reduce((v,p)=>{const year=age-s.eventAge;if(year>=p.maxYears)return v;const months=year===0?Math.max(0,12-p.waiting):12;return v+Number(p.amount)*months*(1+Number(p.benefitGrowth)/100*year);},0);}if(age!==s.eventAge)return 0;if(s.scenario==='home')return enabled.reduce((v,p)=>v+homeBenefit(p,s),0);const reimburse=enabled.filter(p=>p.basis==='reimbursement').reduce((v,p)=>v+Number(p.amount),0);const lump=enabled.filter(p=>p.basis!=='reimbursement').reduce((v,p)=>v+Number(p.amount),0);const cost=s.eventCost*Math.pow(1+s.medicalInflation/100,age-s.age);return Math.min(reimburse,cost)+lump;}
 function simulate(s,policies){validate(s);let funds=Number(s.fund),noEventFunds=Number(s.fund),rows=[],premiumTotal=0,retirementPremium=0,totalCost=0,totalBenefit=0,unknown=false;for(let age=s.age;age<=s.horizon;age++){const years=age-s.age,infl=Math.pow(1+s.inflation/100,years),medInfl=Math.pow(1+s.medicalInflation/100,years),retired=age>=s.retire;const income=retired?s.pension*12*Math.pow(1+s.inflation/100,Math.max(0,s.retire-s.age))*Math.pow(1+s.incomeGrowth/100,Math.max(0,age-Math.max(s.retire,s.age))):s.saving*12*infl;const expenses=retired?s.living*12*infl+s.regularMedical*medInfl:0;const premiums=policies.map(p=>premiumAt(p,age,s));if(premiums.some(x=>x===null))unknown=true;const premium=premiums.reduce((a,x)=>a+(x||0),0);let cost=0,benefit=0;if(s.scenario==='ltc'&&age>=s.eventAge&&age<s.eventAge+s.careYears)cost=s.careMonthly*12*medInfl;else if(s.scenario!=='none'&&s.scenario!=='ltc'&&age===s.eventAge)cost=s.eventCost*medInfl;if(cost>0)benefit=eventBenefits(s,policies,age);const net=income-expenses-premium-cost+benefit;const startFund=funds;const investment=Math.max(funds,0)*s.returnRate/100;funds+=investment+net;noEventFunds+=Math.max(noEventFunds,0)*s.returnRate/100+income-expenses-premium;premiumTotal+=premium;if(retired)retirementPremium+=premium;totalCost+=cost;totalBenefit+=benefit;rows.push({age,retired,income,expenses,premium,cost,benefit,net,startFund,investment,fund:funds,baseFund:noEventFunds,realFund:funds/infl,unknown:premiums.some(x=>x===null)});}
 const atEvent=policies.filter(p=>active(p,s.eventAge,s));const coverage={};for(const type of Object.keys(types))coverage[type]=atEvent.filter(p=>p.type===type).reduce((a,p)=>a+Number(p.amount),0);
 const lifeNeed=Math.max(0,s.debt+s.support-s.familyAssets);return {rows,unknown,premiumTotal,retirementPremium,totalCost,totalBenefit,eventGap:Math.max(0,totalCost-totalBenefit),lifeNeed,lifeGap:Math.max(0,lifeNeed-coverage.life),coverage,currentPremium:rows[0].premium,firstShortfall:rows.find(r=>r.retired&&r.net<0)?.age??null,exhausted:rows.find(r=>r.fund<0)?.age??null,endFund:funds};}
 function priority(age,hasFamily){return [{type:'life',level:hasFamily?'依家庭責任':'視需要',text:hasFamily?'先核對債務與配偶／家屬生活費，再設定死亡保障。':'家庭責任較低時，依配偶需要、負債與資產安排保額。'},{type:'accident',level:'檢視延續',text:'核對高齡續保、骨折與傷害醫療；疾病引起事故仍須按條款認定。'},{type:'medical',level:'優先檢視',text:age>=65?'先維持有效保障，確認保費可負擔及門診、雜費限制。':'確認重大自費缺口，以及保障能否延續到退休後。'},{type:'cancer',level:'檢視一次金',text:'核對癌症分級、首年限制、等待期與保障期限。'},{type:'ltc',level:'優先盤點',text:age>=65?'盤點既有分期金、公共服務與自有照護資金。':'同時比較認定條件、繳費年期與實際給付次數。'},{type:'home',level:'補充評估',text:'在宅急症保單不等於一般居家照顧；另做無法續保情境。'}];}
 const api={types,defaults,rangeRules,validate,samples,active,premiumAt,eventBenefits,simulate,priority};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.RetirementModel=api;
})(typeof window!=='undefined'?window:globalThis);
